### ISSUE TITLE
improve visualization, pt 3

### ISSUE THREAD

**Issue by tcoile** [tcoile/YaleEC#11]
TODO: tooltip labels (nice-looking)
TODO: figure out how to get ALL the data on the page (big Qs on how to do this well) 
TODO: organize visualization code because oh my gosh is it getting all mixed up and sloppy
TODO: trigger zoom on click of tag, child element, if only a centering zoom

**Comment by sarcasticspoon** [comment]
Thoughts for second TODO: 
-https://bl.ocks.org/puzzler10/2531c035e8d514f125c4d15433f79d74, http://bl.ocks.org/donaldh/2920551 -- use the 'tick' function to update a bounding box/circle/blob around each major category

-how to keep blobs from overlapping? just starting them at different positions won't do, because they'll grow... two ideas: 
> 1. put a force simulation on the blobs themselves (they are nodes to a different force simulation, update the node size then update the force simulation itself, perhaps by changing the force as the node size increases) 
> 2. this might work better to keep internal overlap from happening (which I HATE), but see here: https://bl.ocks.org/mbostock/7881887 -- add a force that pulls all nodes within the same group toward each other. Theoretically, the 'group' can just be 'my parent'. Or perhaps just increase the repulsive forces between anything NOT your child, NOT your parent.

**Comment by tcoile** [comment]
after a hellish couple hours, we have this: (sometimes things get uglier before they get better lmao)
<img width="1440" alt="Screen Shot 2020-11-28 at 3 44 41 PM" src="https://user-images.githubusercontent.com/31626867/100525673-a2b8be00-3190-11eb-8975-36aa10f1bfbe.png">

Next step: make these suckers rounded (http://bl.ocks.org/hollasch/9d3c098022f5524220bd84aae7623478 -- this is a fairly recent block that should (fingers crossed) do what I want to do, with minimal edits, which is good because this is a bit past what I'm comfortable doing in d3) 

... and then color them nicely 

... and add interactions

**Comment by tcoile** [comment]
<img width="847" alt="Screen Shot 2020-11-28 at 4 13 11 PM" src="https://user-images.githubusercontent.com/31626867/100526192-9df60900-3194-11eb-8284-331f3ccc9140.png">
hello here we goooo
