### ISSUE TITLE
Improve visualization pt 1

### ISSUE THREAD

**Issue by tcoile** [tcoile/YaleEC#3]
TODO: make it prettier
TODO: make it interactive
TODO: use a subset of the real data

**Comment by sarcasticspoon** [comment]
- uses real data (DONE)
- can drag (DONE), can click on parent nodes to expand and collapse (TODO)
- hovering gives the title of each node (in the most ugly way possible) (DONE)
- is a tree diagram (DONE)

**Comment by tcoile** [comment]
done
